### ISSUE TITLE
Access uncached setting

### ISSUE THREAD

**Issue by troex** [marten/mongoid-app_settings#4]
It would be great to have ability to fetch uncached value on single setting without calling reload. I run disributed system with many instances and when I need to access some specific fields which could be changed unpredicable I have to always call .reload before accessing it. Having direct access for uncached single setting would be great

**Comment by troex** [comment]
maybe something like that:

```ruby
class Settings
  include Mongoid::AppSettings

  setting :email_tracker_report_last_run, default: Time.parse('2010-01-01')

  def self.uncached(setting)
    reload
    send(setting)
  end
end
```

**Comment by troex** [comment]
of even:

```ruby
  def self.uncached
    reload
    self
  end
```

than I could do chaining like the scopes:
```ruby
Settings.uncached.email_tracker_report_last_run
```

**Comment by marten** [comment]
I just pushed v1.2.0 where simply `reload` itself will now return `self`, allowing the method chaining you suggested. Thanks for the tip!

**Comment by troex** [comment]
Thanks for blazing fast delivery!
