### ISSUE TITLE
Enforce data type

### ISSUE THREAD

**Issue by Startouf** [marten/mongoid-app_settings#5]
I want to let my admins change some constants via a form. I thought I could just use the parameters as is, and they would automatically convert to the appropriate data type, but

```ruby
class Constants 
  include Mongoid::AppSettings
  setting :some_number, type: Integer, default: 42
end

Constants.some_number # => 42
Constants.some_number = "42" # Should attempt a conversion to integer
Constants.some_number # => "42", not an integer anymore :(
```

**Comment by marten** [comment]
It's not necessarily *enforcing* but I added limited type support in f5d92b03e1cd7bb09740f7652bda0098457920b7 by just passing that part of the options hash on to Mongoid, which will then try to do the cast. This is also released as version 1.3.0 of this gem.

You won't be able to do validations (which would require a whole bunch of meta-programming trickery if I wanted to be feature-complete with the Mongoid validations API). If you need that, you might be better off using some Interactor-style library ([ActiveInteraction](https://github.com/orgsync/active_interaction) is one I've used, but there are plenty more) to wrap around the actual assignment of values.
